SRC/objects/Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Type__c</fullName>
        <label>Bank Account Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saving</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Salary</fullName>
                </value>
                <value>
                    <fullName>Fixed Deposit</fullName>
                </value>
                <value>
                    <fullName>Recuring Deposit</fullName>
                </value>
                <value>
                    <fullName>NRI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SBI</fullName>
                </value>
                <value>
                    <fullName>Axis Bank</fullName>
                </value>
                <value>
                    <fullName>Union Bank of India</fullName>
                </value>
                <value>
                    <fullName>ICICI</fullName>
                </value>
                <value>
                    <fullName>HDFC</fullName>
                </value>
                <value>
                    <fullName>Bank of Baroda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IFSC_code__c</fullName>
        <label>IFSC code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/classes/BankAccountTriggerHandler.cls
/*
 * Description        :       This class is created as handler class for trigger sending mail and generate account number.
 * Created By         :       Komal Kumawat
 * Created On         :       26/07/22
 * Version Logs       :       V_1.0
*/

public with sharing class BankAccountTriggerHandler
{
    // This method is created to generate account number with prefix.
    public static void accountNumberGenerate( List<Bank_Account__c> accountNumList)
    {
        //Random method to create random account number.
        Integer num1 = Integer.valueOf(Math.random());
        for(Bank_Account__c numList : accountNumList)
        {
            if(numList.Bank_Account_Type__c == 'Saving')
            {
                numList.Account_Number__c = 'SA-'+num1;
            }
            else if(numList.Bank_Account_Type__c == 'Current')
            {
                numList.Account_Number__c = 'CR-'+num1;
            }
            else if(numList.Bank_Account_Type__c == 'Salary')
            {
                numList.Account_Number__c = 'SL-'+num1;
            }
            else if(numList.Bank_Account_Type__c == 'Fixed Deposit')
            {
                numList.Account_Number__c = 'FD-'+num1;
            }
            else if(numList.Bank_Account_Type__c == 'Recuring Deposit')
            {            
                numList.Account_Number__c = 'RD-'+num1;
            }
            else if(numList.Bank_Account_Type__c == 'NRI')
            {
                numList.Account_Number__c = 'NRI-'+num1;
            }
        }
    }

    // This method is created to send Email to Account holder for Account creation.
    public static void emailSendMessage(List<Bank_Account__c> bankAccEmailList)
    {
        List<Messaging.SingleEmailMessage> emailSendMsg = new List<Messaging.SingleEmailMessage>();
        for(Bank_Account__c bankAcct : bankAccEmailList)
        {
            List<String> emailAddress = new List<String>();
            Messaging.SingleEmailMessage emailObject = new Messaging.SingleEmailMessage();
            emailAddress.add(bankAcct.Email_Address__c);
            emailObject.setToAddresses(emailAddress);
            emailObject.setSubject('Congratulations your bank account has been Created!!');
            emailObject.setPlainTextBody('Dear '+bankAcct.Name+',\n\nYour'+bankAcct.Bank_Account_Type__c+' account with '
                                               + bankAcct.Bank_Name__c+' has been created. Your Account Number is '+bankAcct.Account_Number__c 
                                               + 'and your IFSC code is '+ bankAcct.IFSC_code__c+'\n\nThank You.');
            emailSendMsg.add(emailObject);                                   
        }
        Messaging.sendEmail(emailSendMsg);
    }
}