SRC/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Total_Districts__c</fullName>
        <label>Total Districts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/objects/Districts__c.object
<CustomObject>
    <fields>
        <fullName>State_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Name</label>
        <referenceTo>States__c</referenceTo>
        <relationshipLabel>Districts</relationshipLabel>
        <relationshipName>Districts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Districts</label>
    <nameField>
        <label>Districts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/objects/States__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Districts__c</fullName>
        <label>Total Districts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>States</label>
    <nameField>
        <label>States Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/classes/DistrictsTriggerHandler.cls
/* *
   * Purpose        :     This class is created to count the total number of districts when insert, delete, update and populate on State object custom field.
   * Created By     :     Komal Kumawat
   * Created On     :     
   * Version Logs   :     V_1.0         
*/
    public class DistrictsTriggerHandler {
        public static void populateTotalNumberOfDistrictsOnState(List<Districts__c> districtList,  List<Districts__c> districtOldList)
        {
            Set<Id> setOfStateIds = new Set<Id>();
            Set<Id> setOfCountryIds =new Set<Id>();
            // Insert
            for(Districts__c dist : districtList)
            {  
                if(dist.State_Name__c != null)
                {
                    setOfStateIds.add(dist.State_Name__c);
                    setOfCountryIds.add(dist.State_Name__r.Country__r.Name);
                }
            }
            // Update 
            if( districtOldList != null)
            {
                for(Districts__c distOld : districtOldList)
                {
                    if(distOld.State_Name__c != null)
                    {
                        setOfStateIds.add(distOld.State_Name__c);
                    }
                }
            }

            Map<String, Object> stateJsonWrapMap = new Map<String, Object>();
            List<String> districtName = new List<String>();
            for(Districts__c districtData : [Select Id, Name , State_Name__c From Districts__c Where State_Name__c In: setOfStateIds])
            {
                districtName.add(districtData.Name);
            }
            stateJsonWrapMap.put('District Name:-', districtName);
            
            List<States__c> states = new List<States__c>();
            List<States__c> stateList = [Select Id, Name, Total_Districts__c, State_Code__c, Country__r.Total_Districts__c, (Select Id, Name From Districts__r) From States__c Where Id In : setOfStateIds];
            States__c stateObj = new States__c();
            for(States__c stateData : stateList)
            {
                if(setOfStateIds != null)
                {
                    stateData.Total_Districts__c = stateData.Districts__r.size();
                    states.add(stateData);
                    System.debug('Data--'+stateData);
                    stateJsonWrapMap.put('Total Districts-',stateData.Districts__r.size());
                    stateJsonWrapMap.put('State Code-', stateData.State_Code__c);
                    stateJsonWrapMap.put('State Name-', stateData.Name);   
                }
            }

            List<Country__c> countries = new List<Country__c>();
            List<Country__c> countryList = [Select Id, Name, Total_Districts__c, (Select Id, Name From States__r) From Country__c Where Id In : setOfCountryIds];
            for(Country__c countryData : countryList)
            {
                if(setOfStateIds != null)
                {
                    countryData.Total_Districts__c = countryData.States__r.size();
                    countries.add(countryData);
                    System.debug('Data--'+countryData);
                }
            }
            if(states.size() > 0)
            {
                update states;
            }
            if(countries.size() > 0)
            {
                update countries;
            }
            System.debug('Data==='+ districtName);
            stateObj.State_JSON_Data__c = JSON.serialize(stateJsonWrapMap);
            System.debug('@@@ JSON STATE DATA WRAP ' +JSON.serialize(stateJsonWrapMap));
        }
    }