SRC/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{000000}</displayFormat>
        <label>Transaction Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/classes/Search_Transactions_Test.cls
/**
*  Description     : This test class is created to test fuctionality of Search Transactions Controller on vf page . 
*
*  Created By      : Komal Kumawat
*
*  Created Date    : 20 October 2022
*  
*  Revision Log    : V+1.0 : 
*  
**/

@isTest(seeAllData = false)
private class Search_Transactions_Test {
    @testSetup
    private static void testData() {
        List<Contact> listOfContact = new List<Contact>();
        Contact con = new Contact();
        con.LastName = 'Vijay Kumar';
        con.Contact_Status__c = 'Active';
        con.Email = 'vijaykumar@gmail.com';
        listOfContact.add(con); 
        insert listOfContact;
    }
    @isTest
    public static void testContact(){
        List<Contact> listOfConId = new List<Contact>([SELECT Id,LastName FROM Contact WHERE  LastName = 'Vijay Kumar']);
        List<Transaction_Entry__c> listOfCreditEntry = new List<Transaction_Entry__c>();
        Transaction_Entry__c tran  =  new Transaction_Entry__c();
        tran.Contact__c = listOfConId[0].id;
        tran.Amount__c = 500;
        tran.Transaction_Date__c = system.today();
        tran.Type__c = 'Debit';
        tran.Status__c = 'Pending';
        insert tran;

        Search_Transaction_Controller searchVFTnx = new Search_Transaction_Controller();
        searchVFTnx.resetFilter();
        searchVFTnx.next();
        searchVFTnx.last();
        searchVFTnx.previous();
        searchVFTnx.selectTheOption();
        searchVFTnx.getStatus();

    }
}